ARG SCHEME=chibi
FROM docker.io/debian:trixie AS build
RUN apt-get update && apt-get install -y \
    build-essential git ca-certificates wget
WORKDIR /build
RUN wget https://gitlab.com/-/project/6808260/uploads/094ce726ce3c6cf8c14560f1e31aaea0/akku-1.1.0.amd64-linux.tar.xz && tar -xf akku-1.1.0.amd64-linux.tar.xz
WORKDIR /build/akku-1.1.0.amd64-linux
RUN ./install.sh
WORKDIR /build
RUN wget https://ftp.gnu.org/gnu/make/make-4.4.tar.gz && tar -xf make-4.4.tar.gz
WORKDIR /build/make-4.4
ENV PATH=/root/.local:${PATH}
RUN ./configure --prefix=/root/.local
RUN make
run make install
WORKDIR /build
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1
WORKDIR /build/chibi-scheme
RUN make PREFIX=/root/.local
RUN make PREFIX=/root/.local install
RUN apt-get install -y plocate libcurl3t64-gnutls
RUN cp /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.3 /root/.local/lib/libcurl.so.3
RUN cp -r /usr/lib/x86_64-linux-gnu/* /root/.local/lib/

ARG SCHEME=chibi
FROM docker.io/schemers/${SCHEME}:head
COPY --from=build /root/.local /root/.local
ENV PATH=/root/.local/bin:${PATH}
ENV LD_LIBRARY_PATH=/root/.local/lib
WORKDIR /workdir
COPY Makefile Makefile
COPY test.scm test.scm
COPY scheme-venv scheme-venv

