ARG IMG=chibi
FROM docker.io/schemers/${IMG}
RUN apt-get update && apt-get install -y \
    build-essential git wget ca-certificates guile-3.0 guile-3.0-dev libcurl4 \
    xz-utils

WORKDIR /build
RUN wget https://gitlab.com/-/project/6808260/uploads/094ce726ce3c6cf8c14560f1e31aaea0/akku-1.1.0.amd64-linux.tar.xz && tar -xf akku-1.1.0.amd64-linux.tar.xz
RUN git clone https://github.com/ashinn/chibi-scheme.git --depth=1

WORKDIR /build/akku-1.1.0.amd64-linux
RUN ./install.sh

WORKDIR /build/chibi-scheme
RUN make
RUN make install

WORKDIR /workdir
RUN mkdir -p ${HOME}/.snow && echo "()" > ${HOME}/.snow/config.scm
ENV PATH=/root/.local/bin:${PATH}
ENV LD_LIBRARY_PATH=/root/.local/lib
COPY Makefile .
COPY test.scm .
COPY test.sps .
COPY compile-test.scm .
COPY compile-test.sps .
COPY scheme-venv .


